[package]
name = "color-backtrace"
version = "0.2.3"
authors = ["Joel Höner <athre0z@zyantific.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/athre0z/color-backtrace"
description = "Colorful panic backtraces"
readme = "README.md"

keywords = [
    "backtrace",
    "color",
    "colour",
    "stacktrace",
    "pretty",
]

[[example]]
name = "failure"
required-features = ["failure"]

[features]
failure-bt = ["failure"]

[dependencies]
term = "0.6"
atty = "0.2"
failure = { version = "0.1", optional = true }

[target.'cfg(unix)'.dependencies]
backtrace = { version = "0.3", features = ["gimli-symbolize"] }

[target.'cfg(not(unix))'.dependencies]
backtrace = { version = "0.3" }
